### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by metronom72** [jackc/tern#21]
How can I use  `tern` command  in the windows?
Maybe, how can I create alias in windows?

**Comment by jackc** [comment]
Assuming you have Go already installed you should be able to install it the same way as on Linux.

```
go get -u github.com/jackc/tern
```

If you have the $GOPATH/bin directory in your PATH then you can run the `tern` command from anywhere.

**Comment by metronom72** [comment]
Thank you. I'll close issue. Ok?
