### ISSUE TITLE
port in config file not respected

### ISSUE THREAD

**Issue by gsmcwhirter** [jackc/tern#26]
I have a non-standard port for a postgres server and specifying it in the tern.conf file did not pass it through to the connection properly (it still tried to use 5432). Specifying the custom port with `--port` on the command line did work.

**Comment by jackc** [comment]
I believe this was already fixed on master in a9992da but I hadn't tagged a release with it. I've just tagged `v1.12.2` which should resolve this issue.

**Comment by gsmcwhirter** [comment]
Seems to work with the v1.12.2, thanks. (side note, the v1.12.2 binary reports its version as 1.12.3 with `tern version` -- not a big deal, just something odd)

**Comment by jackc** [comment]
Whoops. I made a typo on the version number. I just tagged `v1.12.3` to fix the mismatch. No other changes.
