### ISSUE TITLE
Feature Request: Parse entire DSN from environment variable

### ISSUE THREAD

**Issue by mattrasband** [jackc/tern#39]
A useful feature might be to allow parsing the DSN fully from the environment, as a decent number of services expose something like `DATABASE_URL` which is often in a url format. In those cases, it's more difficult to manually parse out the pieces into a config file.

**Comment by lukecyca** [comment]
I worked around this by making my entire config file just:

```
[database]
conn_string = {{env "DATABASE_URI"}}
```
