### ISSUE TITLE
Migrations not actually run in a transaction?

### ISSUE THREAD

**Issue by Preetam** [jackc/tern#44]
Reading the code for migration, it looks like a transaction is started here:

https://github.com/jackc/tern/blob/ebefbe44196db4180c0ce4ef4244e95d01dc48a8/migrate/migrate.go#L339

but `tx` is not actually used to execute the SQL, so the migration is not actually run within a transaction.

https://github.com/jackc/tern/blob/ebefbe44196db4180c0ce4ef4244e95d01dc48a8/migrate/migrate.go#L352

@jackc: Am I reading that wrong or is there a bug here?

**Comment by Preetam** [comment]
Oh, is it because there is no connection pooling so everything's happening in the same connection?

**Comment by jackc** [comment]
Yes. Since it is a single connection it will be correctly executed even though the code does look suspicious. That code could be made clearer. But I'm also hoping to eliminate explicit transaction handling altogether. See #43.

**Comment by Preetam** [comment]
Thanks!
